project_id = "phvduifvymozqiqwvajj"

[functions.send-kyc-completion-notification]
verify_jwt = false

[functions.gmail-auth-start]
verify_jwt = false

[functions.gmail-auth-callback]
verify_jwt = false

[functions.sync-booking-gmail]
verify_jwt = false

[functions.send-reservation-notification]
verify_jwt = true

[functions.allocate-unit]
verify_jwt = false

[functions.push-availability-booking-com]
verify_jwt = false

[functions.send-mid-stay-cleaning-notifications]
verify_jwt = false

[functions.send-checkin-notification]
verify_jwt = false

[functions.send-checkout-notification]
verify_jwt = false

[functions.send-cancellation-notification]
verify_jwt = false
